version: 2.1
orbs:
  kubernetes: circleci/kubernetes@0.12.0
  aws-cli: circleci/aws-cli@2.0.3
 
jobs:
  test_job:
    working_directory: ~/repo
    docker:
      - image: circleci/golang:1.17.2
    environment:
      GO111MODULE: "on"
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: make install
      - run:
          name: Create words dict
          command: |
            sudo apt install --reinstall wamerican
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Run test
          command: |
            make test
      - store_test_results:
          path: ./coverage.out


workflows:
  test-deploy-wf:
    jobs:
      - test_job:
          context: eu-west-1
