// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	config "github.com/blitzshare/blitzshare.bootstrap.client.cli/app/config"
	blitzshare "github.com/blitzshare/blitzshare.bootstrap.client.cli/app/services/blitzshare"

	mock "github.com/stretchr/testify/mock"
)

// BlitzshareApi is an autogenerated mock type for the BlitzshareApi type
type BlitzshareApi struct {
	mock.Mock
}

// GetPeerAddr provides a mock function with given fields: _a0, oneTimePass
func (_m *BlitzshareApi) GetPeerAddr(_a0 *config.AppConfig, oneTimePass *string) *blitzshare.PeerAddress {
	ret := _m.Called(_a0, oneTimePass)

	var r0 *blitzshare.PeerAddress
	if rf, ok := ret.Get(0).(func(*config.AppConfig, *string) *blitzshare.PeerAddress); ok {
		r0 = rf(_a0, oneTimePass)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*blitzshare.PeerAddress)
		}
	}

	return r0
}

// RegisterAsPeer provides a mock function with given fields: _a0, multiAddr, oneTimePass
func (_m *BlitzshareApi) RegisterAsPeer(_a0 *config.AppConfig, multiAddr string, oneTimePass string) bool {
	ret := _m.Called(_a0, multiAddr, oneTimePass)

	var r0 bool
	if rf, ok := ret.Get(0).(func(*config.AppConfig, string, string) bool); ok {
		r0 = rf(_a0, multiAddr, oneTimePass)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
