// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ClipBoard is an autogenerated mock type for the ClipBoard type
type ClipBoard struct {
	mock.Mock
}

// CopyToClipBoard provides a mock function with given fields: s
func (_m *ClipBoard) CopyToClipBoard(s *string) {
	_m.Called(s)
}
