// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	bufio "bufio"

	config "github.com/blitzshare/blitzshare.bootstrap.client.cli/app/config"
	host "github.com/libp2p/go-libp2p-core/host"

	mock "github.com/stretchr/testify/mock"

	network "github.com/libp2p/go-libp2p-core/network"

	protocol "github.com/libp2p/go-libp2p-core/protocol"
)

// P2p is an autogenerated mock type for the P2p type
type P2p struct {
	mock.Mock
}

// ConnectToBootsrapNode provides a mock function with given fields: conf
func (_m *P2p) ConnectToBootsrapNode(conf *config.AppConfig) *host.Host {
	ret := _m.Called(conf)

	var r0 *host.Host
	if rf, ok := ret.Get(0).(func(*config.AppConfig) *host.Host); ok {
		r0 = rf(conf)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*host.Host)
		}
	}

	return r0
}

// ConnectToPeer provides a mock function with given fields: h, address, _a2
func (_m *P2p) ConnectToPeer(h *host.Host, address *string, _a2 protocol.ID) *bufio.ReadWriter {
	ret := _m.Called(h, address, _a2)

	var r0 *bufio.ReadWriter
	if rf, ok := ret.Get(0).(func(*host.Host, *string, protocol.ID) *bufio.ReadWriter); ok {
		r0 = rf(h, address, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bufio.ReadWriter)
		}
	}

	return r0
}

// StartPeer provides a mock function with given fields: conf, _a1, handler
func (_m *P2p) StartPeer(conf *config.AppConfig, _a1 protocol.ID, handler func(network.Stream)) *host.Host {
	ret := _m.Called(conf, _a1, handler)

	var r0 *host.Host
	if rf, ok := ret.Get(0).(func(*config.AppConfig, protocol.ID, func(network.Stream)) *host.Host); ok {
		r0 = rf(conf, _a1, handler)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*host.Host)
		}
	}

	return r0
}
